spring:
  application:
    name: spring-data-jpa-1
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: sonali
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
   healthcheck:
      enabled: true
   instance:
      hostname: localhost
